apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
- operator/namespace.yaml
- operator/operator-group.yaml
- operator/pipelines-subscription.yaml
- instance/tekton.yaml
- instance/pipeline.yaml
- instance/trigger.yaml
- instance/addon.yaml