apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: config
  namespace: openshift-operators
  labels:
    app.kubernetes.io/instance: pipelines
spec:
  addon:
    params:
      - name: pipelineTemplates
        value: 'true'
      - name: clusterTasks
        value: 'true'
  pipeline:
    params:
      - name: enableMetrics
        value: 'true'
  profile: all
  pruner:
    keep: 2
    resources:
      - pipelinerun
      - taskrun
    schedule: '*/5 * * * *'
  targetNamespace: openshift-pipelines