apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
    name: greeting-app-example
    namespace: demo-namespace
  path: deployment.yaml
