apiVersion: v1
kind: Service
metadata:
  name: greeting-app-example
  namespace: demo-namespace
spec:
  selector:
    app: greeting-app-example
  ports:
  - port: 8080
    name: "http"
    protocol: "TCP"
    targetPort: 8080