apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- operator/namespace.yaml
- operator/operatorgroup.yaml
- operator/subscription.yaml
- instance/apimanager.yaml
