apiVersion: redhatcop.redhat.io/v1alpha1
kind: UserConfig
metadata:
  name: user-developer
spec:
  annotationSelector: {}
  labelSelector:
    matchLabels:
      role: developer
  templates:
    - objectTemplate: |
        apiVersion: v1
        kind: Namespace
        metadata:
          name: {{ .Name }}-dev
        labels:
          size: small
    - objectTemplate: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: {{ .Name }}-dev
          namespace: {{ .Name }}-dev
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: admin
        subjects:
        - kind: User
          apiGroup: rbac.authorization.k8s.io
          name: {{ .Name }}